Information about testnet, infura, metamask
ethereumbook/ethereumbook pull request #297
Opened 2018-03-18 14:41 UTC by AyushyaChitransh

Updated some sections:

 - What is testnet?
 - Using Testnets
 - MetaMask and Testnets
 - Network Provider Infura

I've tried to keep the details short and concise. Feel free to make/suggest corrections.

2018-03-19 13:28 UTC, come-maiz requested changes

2018-03-19 13:28 UTC, elopio commented on ethereum-testnets.asciidoc
> +A test network is used to simulate behavior of ethereum network. There are some publicly available test networks.
I would add articles. Maybe: simulate THE behavior of THE main ethereum network and some variations.

2018-03-19 13:28 UTC, elopio commented on ethereum-testnets.asciidoc
> +When any major change is about to be included in main ethereum network, its tests are mostly done on these test networks.
in THE main ethereum...

2018-03-19 13:28 UTC, elopio commented on ethereum-testnets.asciidoc
> +These test networks are also used by large number of developers for testing their applicactions before deploying them on main network.
by A large.

2018-03-19 13:28 UTC, elopio commented on ethereum-testnets.asciidoc
> +First lets use a public testnet for an easier setup. For using public testnet, you require some testnet ethers
lets -> let's
To use a public testnet

2018-03-20 00:32 UTC, fjrojasgarcia approved these changes
IMHO sounds fine.

2018-03-20 00:36 UTC, merged