Rework some sentences in the What Is Ethereum Section
ethereumbook/ethereumbook pull request #298
Opened 2018-03-18 18:17 UTC by bitsol

Working towards the closure of #275?

2018-03-19 13:35 UTC, come-maiz requested changes

2018-03-19 13:35 UTC, elopio commented on what-is.asciidoc
> +Is is not necessary to understand JavaScript. Programming experience will be very helpful, but is not necessarily required to understand some of these concepts
Is is -> It is

2018-03-19 14:40 UTC, bitsol commented
Fixed! Thanks @elopio.

2018-03-20 00:26 UTC, fjrojasgarcia approved these changes
IMHO sounds fine.

2018-03-20 00:36 UTC, merged