Update raw_tx_demo.js
ethereumbook/ethereumbook pull request #911
Opened 2019-07-25 14:06 UTC by datgrog

Newer ethereumjs-tx version requires `require('ethereumjs-tx').Transaction`

2020-01-11 06:33 UTC, ChrisLinn approved these changes

2020-01-11 06:34 UTC, 0xmountaintop approved these changes

2020-01-11 06:42 UTC, HAOYUatHZ commented
The original code is for ethereumjs-tx@1.3.3

ethereumjs-tx's v2.0.0 changelog states such an API change. (see https://github.com/ethereumjs/ethereumjs-tx/releases/tag/v2.0.0)

for this PR, better also bump the version to v2.0.0
in https://github.com/ethereumbook/ethereumbook/blob/develop/code/web3js/raw_tx/package.json
otherwise it's incompatible with 1.3.3 and can be confusing.

2020-01-11 06:48 UTC, 0xmountaintop requested changes
The original code is for ethereumjs-tx@1.3.3

ethereumjs-tx's v2.0.0 changelog states such an API change. (see https://github.com/ethereumjs/ethereumjs-tx/releases/tag/v2.0.0)

for this PR, better also bump the version to v2.0.0
in https://github.com/ethereumbook/ethereumbook/blob/develop/code/web3js/raw_tx/package.json
otherwise it's incompatible with 1.3.3 and can be confusing.

2020-07-24 14:01 UTC, carlinhocr commented
don't you have a problem with the data:'' field? saying the string should begin with 0x

2021-03-10 10:36 UTC, wbnns approved these changes
@datgrog 

Thank you.

@HAOYUatHZ I bumped `ethereumjs-tx` to `2.0.0` in `package.json`.

2021-03-10 10:38 UTC, merged