Slock.it didn't deploy TheDAO
ethereumbook/ethereumbook pull request #923
Opened 2020-01-18 15:23 UTC by GriffGreen

On April 5th the audited code was released but it was deployed by Daotoshi Nakomoto on April 30th

2020-01-21 01:07 UTC, HAOYUatHZ commented
https://github.com/slockit/DAO/releases
version 1.0 code is official released on April 29th

2020-01-21 01:07 UTC, 0xmountaintop approved these changes

2020-01-21 01:08 UTC, 0xmountaintop requested changes
Sorry I would like to revoke my approval.

As shown in https://github.com/slockit/DAO/releases,
version 1.0 code is actually officially released on April 29th

2020-01-22 11:02 UTC, merged

2020-01-22 11:02 UTC, wbnns commented
@GriffGreen Thank you.

@HAOYUatHZ I revised the text a bit more.