Updated Faucet.sol to 0.6 and updated ch2 dependencies
ethereumbook/ethereumbook pull request #951
Opened 2020-02-16 22:36 UTC by safetyth1rd

1. Updated Faucet.sol to 0.6 based on PR931 from @HAOYUatHZ'
2. updated Chapter to reflect new Faucet.sol. This included:
-updating remix_faucet_load screenshot to reflect new code
-changing references to fallback function to receive function
-changing the paragraph about fallback functions to explain the receive function based on this dsecription: https://solidity.readthedocs.io/en/v0.6.0/contracts.html#receive-ether-function

2020-02-17 01:11 UTC, HAOYUatHZ commented on code/Solidity/Faucet.sol
> +    function () external payable {}
`receive () external payable {}`

2020-02-17 07:07 UTC, safetyth1rd commented on code/Solidity/Faucet.sol
> +    function () external payable {}
fixed in latest commit. good catch!

2020-02-18 12:10 UTC, wbnns requested changes
@safetyth1rd 

Thank you. Noticed a small issue, mentioned in-line.

2020-02-18 12:10 UTC, wbnns commented on 02intro.asciidoc
> +recieve () external payable {}
`recieve` is misspelled here

2020-02-18 16:38 UTC, safetyth1rd commented on 02intro.asciidoc
> +recieve () external payable {}
good catch

2020-02-20 17:26 UTC, merged